fix(proton-ge): Pass `steamDisplayName` with `overrideAttrs`
With https://github.com/NixOS/nixpkgs/pull/551916 merged, it had an error build my system, after investigation, I've found that `nix-citizen` set `steamDisplayName`

```
error: proton-ge-bin: The `steamDisplayName` interface has been changed to an attribute, which is overridable using `overrideAttrs`.
```

Per the PR above, the attribute should be passed using `overrideAttrs` instead of `override`